### ISSUE TITLE
Need to add status of various periodic e2e tests to the README.md

### ISSUE THREAD

**Issue by ibuziuk** [openshiftio/saas-openshiftio#1188]
Currently there are a few jobs which periodically run e2e tests against different clusters e.g. 
https://ci.centos.org/job/devtools-test-e2e-prod-preview.openshift.io-smoketest-pr-us-east-2a-released/
Need to status for all existing periodic jobs to the repos README.md. One could use rh-che README.md [1] as an example:

| Last build        | Description           |
| ------------- |:-------------:|
| [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-rh-che-periodic-prod-2)](https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-2/) | periodic tests against production cluster us-east-2 |
| [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-rh-che-periodic-prod-preview-2a)](https://ci.centos.org/view/Devtools/job/devtools-rh-che-periodic-prod-preview-2a/) | periodic tests against prod-preview cluster us-east-2a |
| [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-rh-che-build-che-credentials-master)](https://ci.centos.org/view/Devtools/job/devtools-rh-che-build-che-credentials-master/) | master build |
| [![Build Status](https://ci.codenvycorp.com/buildStatus/icon?job=rh-che-ci-master)](https://ci.codenvycorp.com/job/rh-che-ci-master/) | build compatibility with upstream |
| [![Build Status](https://ci.centos.org/buildStatus/icon?job=devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io)](https://ci.centos.org/view/Devtools/job/devtools-rh-che-rh-che-compatibility-test-dev.rdu2c.fabric8.io/) | integration tests against latest upstream SNAPSHOT |

[1] https://github.com/redhat-developer/rh-che/blob/master/README.md

**Comment by ibuziuk** [comment]
@ppitonak @ldimaggi will you be able to handle this issue? It would really help to track the status of the service ? Another option would be adding e2e statuses to https://github.com/openshiftio/openshift.io

**Comment by ldimaggi** [comment]
The addition of the [Build Status] markdown element is great!  I just added the BDD tests to the appropriate README file - see pull request: https://github.com/fabric8io/fabric8-test/pull/1231

Can we do the same for the E2E tests?

**Comment by ibuziuk** [comment]
@ldimaggi it would be great to have all important periodic e2e tests status in a single place IMO. Probably https://github.com/openshiftio/openshift.io/blob/master/README.md is the best candidate. wdyt ?

**Comment by kpiwko** [comment]
+1 @ibuziuk.

We do have this at single place now in Zabbix but huge +1 for badges in readme files.

**Comment by ppitonak** [comment]
@sanketpathak volunteered to implement it.

**Comment by ibuziuk** [comment]
@sanketpathak any updates ?

**Comment by sanketpathak** [comment]
It's almost ready. I'll be raising the PR soon.

**Comment by sanketpathak** [comment]
As suggested by @ppitonak @ljelinkova I've created the E2e test result matrix as a wiki page. Since others are monitoring the test result in readme shouldn't we do the same for consistency purposes

**Comment by ibuziuk** [comment]
@sanketpathak Thanks for handling this issue. wiki works fine for me as long as it contains all the CI jobs that we currently have for tests. If you do not plan to add anything else feel free to close the issue

**Comment by sanketpathak** [comment]
@ibuziuk Thanks for the answer. I don't have permission to close the issue. Please can you do it on my behalf
