### ISSUE TITLE
CI checks not running, preventing merge

### ISSUE THREAD

**Issue by rkratky** [openshiftio/saas-openshiftio#934]
I have a trivial PR open [1] for docs update, but I can't merge it because the required checks are not running. It's been sitting there for over a day. Could someone please check what the problem is?

[1] https://github.com/openshiftio/saas-openshiftio/pull/925

**Comment by jmelis** [comment]
I ran it again and it looks like worked. I don't know why it got stuck but it looks like a random failure.

**Comment by rkratky** [comment]
@jmelis, the branch was out of sync with master, so I updated it, and the CI checks are not starting again. Looks more than random to me.

**Comment by jmelis** [comment]
You are right, you were missing from the admins list https://github.com/openshiftio/openshiftio-cico-jobs/pull/700

**Comment by jmelis** [comment]
you have been added. Can you verify that it works now?

**Comment by rkratky** [comment]
Works, thanks.
